// Action types for creature
export const FETCH_CREATURES_START = 'FETCH_CREATURES_START';
export const FETCH_CREATURES_SUCCESS = 'FETCH_CREATURES_SUCCESS';
export const FETCH_CREATURES_ERROR = 'FETCH_CREATURES_ERROR';

// Action for fetch one creature
export const FETCH_CREATURES_BY_ID = 'FETCH_CREATURES_BY_ID';
export const FETCH_CREATURES_BY_ID_START = 'FETCH_CREATURES_BY_ID';
export const FETCH_CREATURES_BY_ID_SUCCESS = 'FETCH_CREATURES_BY_ID';
export const FETCH_CREATURES_BY_ID_ERROR = 'FETCH_CREATURES_BY_ID';


// Action types for filter data
export const FETCH_FILTER_DATA = 'FETCH_FILTER_DATA';
export const FETCH_FILTER_DATA_START = 'FETCH_FILTER_DATA_START';
export const FETCH_FILTER_DATA_SUCCESS = 'FETCH_FILTER_DATA_SUCCESS';
export const FETCH_FILTER_DATA_ERROR = 'FETCH_FILTER_DATA_ERROR';

// Action for delete error
export const DELETE_ERROR = 'DELETE_ERROR';

// Action Fetch HasTag ID
export const FETCH_START = 'FETCH_START';
export const FETCH_HASHTAG_ID_SUCCESS = 'FETCH_HASHTAG_ID_SUCCESS';
export const FETCH_ERROR = 'FETCH_ERROR';

//action fetch post
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_ERROR = 'FETCH_POST_ERROR';
export const FETCH_POST_DETAIL_SUCCESS = 'FETCH_POST_DETAIL_SUCCESS';