// Action for delete error
export const DELETE_ERROR = 'DELETE_ERROR';

// Action Fetch HasTag ID
export const FETCH_START = 'FETCH_START';
export const FETCH_HASHTAG_ID_SUCCESS = 'FETCH_HASHTAG_ID_SUCCESS';
export const FETCH_ERROR = 'FETCH_ERROR';

//action fetch post
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_ERROR = 'FETCH_POST_ERROR';
export const FETCH_POST_DETAIL_SUCCESS = 'FETCH_POST_DETAIL_SUCCESS';
export const CHANGE_POST_START = 'CHANGE_POST_START';
export const CHANGE_POST_SUCCESS = 'CHANGE_POST_SUCCESS';
export const CHANGE_POST_ERROR = 'CHANGE_POST_ERROR';
export const POST_END_FORM = 'POST_END_FORM';
export const CREATE_POST = 'CREATE_POST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const SET_POSTS_LIST = 'SET_POSTS_LIST';

//action fetch question
export const FETCH_QUESTION_SUCCESS = 'FETCH_QUESTION_SUCCESS';
export const FETCH_QUESTION_ERROR = 'FETCH_QUESTION_ERROR';
export const FETCH_QUESTION_DETAIL_SUCCESS = 'FETCH_QUESTION_DETAIL_SUCCESS';
export const CHANGE_QUESTION_START = 'CHANGE_QUESTION_START';
export const CHANGE_QUESTION_SUCCESS = 'CHANGE_QUESTION_SUCCESS';
export const CHANGE_QUESTION_ERROR = 'CHANGE_QUESTION_ERROR';
export const QUESTION_END_FORM = 'QUESTION_END_FORM';
export const CREATE_QUESTION = 'CREATE_QUESTION';
export const DELETE_QUESTION_SUCCESS = 'DELETE_QUESTION_SUCCESS';
export const SET_QUESTIONS_LIST = 'SET_QUESTIONS_LIST';

//action fetch answer
export const FETCH_ANSWER_SUCCESS = 'FETCH_ANSWER_SUCCESS';
export const FETCH_ANSWER_ERROR = 'FETCH_ANSWER_ERROR';
export const FETCH_ANSWER_DETAIL_SUCCESS = 'FETCH_ANSWER_DETAIL_SUCCESS';
export const CHANGE_ANSWER_START = 'CHANGE_ANSWER_START';
export const CHANGE_ANSWER_SUCCESS = 'CHANGE_ANSWER_SUCCESS';
export const CHANGE_ANSWER_ERROR = 'CHANGE_ANSWER_ERROR';
export const ANSWER_END_FORM = 'ANSWER_END_FORM';
export const CREATE_ANSWER = 'CREATE_ANSWER';
export const DELETE_ANSWER_SUCCESS = 'DELETE_ANSWER_SUCCESS';
export const SET_ANSWERS_LIST = 'SET_ANSWERS_LIST';

//action fetch event
export const FETCH_EVENT_SUCCESS = 'FETCH_EVENT_SUCCESS';
export const FETCH_EVENT_ERROR = 'FETCH_EVENT_ERROR';
export const FETCH_EVENT_DETAIL_SUCCESS = 'FETCH_EVENT_DETAIL_SUCCESS';
export const CHANGE_EVENT_START = 'CHANGE_EVENT_START';
export const CHANGE_EVENT_SUCCESS = 'CHANGE_EVENT_SUCCESS';
export const CHANGE_EVENT_ERROR = 'CHANGE_EVENT_ERROR';
export const EVENT_END_FORM = 'EVENT_END_FORM';
export const CREATE_EVENT = 'CREATE_EVENT';
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';
export const SET_EVENTS_LIST = 'SET_EVENTS_LIST';

// category
export const CATEGORY_START = 'CATEGORY_START';
export const CATEGORY_ERROR = 'CATEGORY_ERROR';
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS';
export const SET_CATEGORY_LIST = 'SET_CATEGORY_LIST';

// Login 
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOG_OUT = 'LOG_OUT';

// admin
export const EDIT_CREATURE_START = 'EDIT_CREATURE_START';

// loader
export const SET_LOADER = 'SET_LOADER';

// list image
export const SET_LIST_IMAGES = 'SET_LIST_IMAGES';

// list Users
export const SET_LIST_USERS = 'SET_LIST_USERS';


// list species 
export const SET_LIST_SPECIES = 'SET_LIST_SPECIES';

// list groups
export const SET_LIST_GROUPS = 'SET_LIST_GROUPS';

// list orders

export const SET_LIST_ORDERS = 'SET_LIST_ORDERS';

//list FAMILIES
export const SET_LIST_FAMILIES = 'SET_LIST_FAMILIES';

// fetch creature category 
export const SET_CREATURES_CATEGORIES = 'SET_CREATURES_CATEGORIES';

//
export const SET_LIST_CREATURES = 'SET_LIST_CREATURES';

// footprint
export const SET_LIST_FOOTPRINTS = 'SET_LIST_FOOTPRINTS';

// TimberSample
 export const SET_TIMBER_SAMPLE = 'SET_TIMBER_SAMPLE';

 export const SET_LIST_FEEDBACK = 'SET_LIST_FEEDBACK';

// Contributions
export const SET_LIST_CONTRIBUTES = "SET_LIST_CONTRIBUTES";