// Action types for creature
export const FETCH_CREATURES_START = 'FETCH_CREATURES_START';
export const FETCH_CREATURES_SUCCESS = 'FETCH_CREATURES_SUCCESS';
export const FETCH_CREATURES_ERROR = 'FETCH_CREATURES_ERROR';
export const FETCH_CREATURES_REDBOOK_SUCCESS = 'FETCH_CREATURES_REDBOOK_SUCCESS';
export const FETCH_CREATURES_REDBOOK_START = 'FETCH_CREATURES_REDBOOK_START';


// Action for fetch one creature
export const FETCH_CREATURES_BY_ID = 'FETCH_CREATURES_BY_ID';
export const FETCH_CREATURES_BY_ID_START = 'FETCH_CREATURES_BY_ID';
export const FETCH_CREATURES_BY_ID_SUCCESS = 'FETCH_CREATURES_BY_ID';
export const FETCH_CREATURES_BY_ID_ERROR = 'FETCH_CREATURES_BY_ID';


// Action types for filter data
export const FETCH_FILTER_DATA = 'FETCH_FILTER_DATA';
export const FETCH_FILTER_DATA_START = 'FETCH_FILTER_DATA_START';
export const FETCH_FILTER_DATA_SUCCESS = 'FETCH_FILTER_DATA_SUCCESS';
export const FETCH_FILTER_DATA_ERROR = 'FETCH_FILTER_DATA_ERROR';

// Action for delete error
export const DELETE_ERROR = 'DELETE_ERROR';

// Action Fetch HasTag ID
export const FETCH_START = 'FETCH_START';
export const FETCH_HASHTAG_ID_SUCCESS = 'FETCH_HASHTAG_ID_SUCCESS';
export const FETCH_ERROR = 'FETCH_ERROR';

//action fetch post
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_ERROR = 'FETCH_POST_ERROR';
export const FETCH_POST_DETAIL_SUCCESS = 'FETCH_POST_DETAIL_SUCCESS';


// Species start
export const SPECIES_START = 'SPECIES_START';
export const SPECIES_ERROR = 'SPECIES_ERROR';
export const FETCH_SPECIES_SUCCESS = 'FETCH_SPECIES_SUCCESS';

// category
export const CATEGORY_START = 'CATEGORY_START';
export const CATEGORY_ERROR = 'CATEGORY_ERROR';
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS';

// National parks
export const NATIONAL_PARKS_START = "NATIONAL_PARKS_START";
export const NATIONAL_PARKS_ERROR = "NATIONAL_PARKS_ERROR";
export const FETCH_NP_BY_ID_SUCCES = "FETCH_NP_BY_ID_SUCCES";
export const FETCH_NP_COORDS_SUCCESS = 'FETCH_NP_COORDS_SUCCESS';

// AUTHOR
export const AUTHOR_START = "AUTHOR_START";
export const AUTHOR_ERROR = "AUTHOR_ERROR";
export const FETCH_AUTHORS_SUCCESS = "FETCH_AUTHORS_SUCCESS";

// Latin dic
export const LATIN_DIC_START = 'LATIN_DIC_START';
export const LATIN_DIC_ERROR = 'LATIN_DIC_ERROR';
export const SEARCH_LATIN_DIC_SUCCESS = 'LATIN_DIC_SUCCESS';

// Login 
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOG_OUT = 'LOG_OUT';

// admin
export const EDIT_CREATURE_START = 'EDIT_CREATURE_START';